#index:
#    path: /
#    controller: App\Controller\DefaultController::index
index:
    path: /forum
    controller: App\Controller\ForumController::index

topic:
    path: /topic
    controller: App\Controller\TopicController::topic

